### ISSUE TITLE
Lags, forces to restart my laptop.

### ISSUE THREAD

**Issue by LeftyyGD** [Sachit71/Discord-Lite#10]
I try to open it (1.2 ver) - it causes such lags that it's unusable.
Didn't try 1.0, cuz it doesn't have vc support.

Eventually there's a bunch of errors, even blank ones. One said something along the lines of "This application didn't run properly" (random translation attempt, i have win10 in Polish)

I own an Acer E5-575G (i5-7200U, 940MX, 8GB RAM + SSD)

**Comment by Sachit71** [comment]
Heya this issue has already been reported and will be solved in the new v1.2 installer which will be delivered shortly, you will be updated when the release is ot, thank you for your patience and sorry for any inconvenience caused.

**Comment by Sachit71** [comment]
Will be closing and redirecting to the original issue.
